-- Criar tabela de marcas
CREATE TABLE marcas(
       codigo_marca NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
       nome_marca VARCHAR2(30)    
);

-- Adicionar uma chave primária
ALTER TABLE marcas 
ADD CONSTRAINT codigo_marca_pk PRIMARY KEY(codigo_marca);

-- Cadastrar marca
INSERT INTO marcas(nome_marca) VALUES ('Apple');
INSERT INTO marcas(nome_marca) VALUES ('Samsung');
INSERT INTO marcas(nome_marca) VALUES ('Motorola');
INSERT INTO marcas(nome_marca) VALUES ('Xiaomi');

-- Selecionar marcas
SELECT * FROM marcas;



-- Criar tabela de produtos
CREATE TABLE produtos(
       codigo_produto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
       nome_produto VARCHAR2(50),
       valor_produto NUMBER,
       codigo_marca NUMBER
);

-- Adicionar uma chave primária
ALTER TABLE produtos
ADD CONSTRAINT codigo_produto_pk PRIMARY KEY(codigo_produto);


-- Adicionar uma chave estrangeira
ALTER TABLE produtos
ADD CONSTRAINT codigo_marca_fk 
FOREIGN KEY (codigo_marca) REFERENCES marcas(codigo_marca);

-- Cadastrar produtos
INSERT INTO produtos (nome_produto,valor_produto,codigo_marca)VALUES('Galaxy S22 Ultra',5000, 2);
INSERT INTO produtos (nome_produto,valor_produto,codigo_marca)VALUES('iPhone 13',7000, 1);
INSERT INTO produtos (nome_produto,valor_produto,codigo_marca)VALUES('Moto G8',2700,3);
INSERT INTO produtos (nome_produto,valor_produto,codigo_marca)VALUES('iPhone Pro Max',6900 ,1);
INSERT INTO produtos (nome_produto,valor_produto,codigo_marca)VALUES('Galaxy FE',3200 ,2);

-- Listar produtos
SELECT * FROM produtos;

-- Inner Join - Vinculando dados entre tabelas
SELECT 
   produtos.nome_produto,
   produtos.valor_produto,
   marcas.nome_marca
FROM produtos 
INNER JOIN marcas
ON produtos.codigo_marca = marcas.codigo_marca;

-- Agrupar dados
SELECT 
   marcas.nome_marca,
   COUNT(produtos.codigo_marca)
 FROM marcas 
 INNER JOIN produtos
 ON marcas.codigo_marca = produtos.codigo_marca
 GROUP BY (marcas.nome_marca);
 




