CREATE TABLE cargos(
       codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
       nome VARCHAR2(50),
       salario NUMBER,
       CONSTRAINT pk_codigo PRIMARY KEY (codigo)
);

INSERT INTO cargos (nome,salario) VALUES ( 'Desenvolvedor', 3000.00);
INSERT INTO cargos (nome,salario) VALUES ( 'Analista', 4500.00);
INSERT INTO cargos (nome,salario) VALUES ( 'Arquiteto de Software', 6200.00);
INSERT INTO cargos (nome,salario) VALUES ( 'Administrador de Banco de Dados', 7700.00);
INSERT INTO cargos (nome,salario) VALUES ( 'Gerente de Projetos', 9000.00);



CREATE TABLE colaboradores (
       codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
       nome VARCHAR2(40),
       nascimento DATE,
       cargo NUMBER,
       estado VARCHAR2(2),
       cidade VARCHAR2(20),
       genero VARCHAR2(10),
       CONSTRAINT pk_codigo_colaboradores PRIMARY KEY (codigo)
);

ALTER TABLE colaboradores
ADD CONSTRAINT codigo_cargo_fk 
FOREIGN KEY (cargo) REFERENCES cargos(codigo);


INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Jefferson', TO_DATE('1973/05/19','YYYY-MM-DD'), 1, 'SC', 'Blumenau', 'Masculino');
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Larissa', TO_DATE('1991/01/22','YYYY-MM-DD'), 5, 'SC', 'Joinville', 'Feminino');
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Cleber', TO_DATE('1987/03/18','YYYY-MM-DD'), 2, 'PR', 'Curitiba', 'Masculino');
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Luciano', TO_DATE('1995/08/09','YYYY-MM-DD'), 1, 'SC', 'Blumenau', 'Masculino');
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Jéssica', TO_DATE('1988/08/22','YYYY-MM-DD'), 4, 'SC', 'Florianópolis', 'Feminino');
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Guilherme', TO_DATE('1982/11/16','YYYY-MM-DD'), 2, 'SC', 'Blumenau', 'Masculino');
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Marcelo', TO_DATE('1993/04/15','YYYY-MM-DD'), 2, 'PR', 'Londrina', 'Masculino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Brenda', TO_DATE('1992/02/17','YYYY-MM-DD'), 1, 'SC', 'Joinville', 'Feminino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Rebeca', TO_DATE('1984/06/26','YYYY-MM-DD'), 4, 'SC', 'Blumenau', 'Feminino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Cristiano', TO_DATE('1983/07/02','YYYY-MM-DD'), 1, 'SC', 'Florianópolis', 'Masculino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Éder', TO_DATE('1991/11/10','YYYY-MM-DD'), 1, 'SC', 'Blumenau', 'Masculino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('William', TO_DATE('1992/12/17','YYYY-MM-DD'), 2, 'PR', 'Curitiba', 'Masculino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Vanessa', TO_DATE('1996/09/29','YYYY-MM-DD'), 1, 'SC', 'Blumenau', 'Feminino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Robson', TO_DATE('1984/05/30','YYYY-MM-DD'), 1, 'PR', 'Londrina', 'Masculino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Tatiana', TO_DATE('1990/02/03','YYYY-MM-DD'), 5, 'PR', 'Curitiba', 'Feminino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Henrique', TO_DATE('1999/10/07','YYYY-MM-DD'), 1, 'SC', 'Blumenau', 'Masculino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Lorena', TO_DATE('1996/04/20','YYYY-MM-DD'), 1, 'SC', 'Joinville', 'Feminino');
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Carla', TO_DATE('1988/09/28','YYYY-MM-DD'), 4, 'PR', 'Curitiba', 'Feminino'); 
INSERT INTO colaboradores (nome,nascimento,cargo,estado,cidade,genero) VALUES ('Alexandre', TO_DATE('1982/07/17','YYYY-MM-DD'), 2, 'SC', 'Blumenau', 'Masculino');

-- Listar nome, cargo e salário

SELECT
   colaboradores.nome,
   cargos.nome,
   cargos.salario
FROM colaboradores
INNER JOIN cargos
ON colaboradores.cargo = cargos.codigo;

-- Listar todos os cargos e a quantidade de colaboladores em cada cargo 

SELECT
   cargos.nome,
   COUNT(colaboradores.cargo)
FROM cargos
LEFT JOIN colaboradores
ON cargos.codigo = colaboradores.cargo
GROUP BY cargos.nome;



-- Nome e data de nascimento de quem tem entre 20 e 30 anos

SELECT 
   nome,
   nascimento
FROM colaboradores
WHERE 2022 - TO_CHAR(nascimento,'YYYY') < 30 AND 2022 - TO_CHAR(nascimento,'YYYY') > 20

-- Quantidade de pessoas em cada estado

SELECT 
estado,
COUNT(*)
FROM colaboradores
GROUP BY estado


-- Quantidade de pessoas em cada cidade

SELECT 
cidade,
COUNT(*)
FROM colaboradores
GROUP BY cidade

-- Quantidade de mulheres com mais de 30 anos que atuam no paraná

SELECT 
COUNT(*)
FROM colaboradores 
WHERE 2022 - TO_CHAR(nascimento,'YYYY') > 30 AND estado = 'PR'

-- Média dos salários de todos os colaboradores

SELECT 
AVG(cargos.salario)
FROM colaboradores
INNER JOIN cargos
ON cargos.codigo = colaboradores.cargo;

-- Colaborador mais velho

SELECT *
FROM colaboradores
INNER JOIN cargos
ON cargos.codigo = colaboradores.cargo
WHERE nascimento = (SELECT MIN(nascimento) FROM colaboradores);

-- Quantidade de pessoas da década de 90

SELECT 
COUNT(*)
FROM colaboradores
WHERE TO_CHAR(nascimento,'YYYY') >= 1990 AND TO_CHAR(nascimento,'YYYY') <= 1999;

-- Excluir tabela

DROP TABLE colaboradores;
DROP TABLE cargos;
