CREATE TABLE marcas (
       codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
       nome VARCHAR2(20),
       CONSTRAINT marcas_codigo_pk PRIMARY KEY (codigo)
);

CREATE TABLE produtos(
       codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
       nome VARCHAR2(40),
       valor NUMBER,
       estoque NUMBER,
       codigomarca NUMBER,
       CONSTRAINT produtos_codigo_pk PRIMARY KEY (codigo),
       CONSTRAINT produtos_codigomarca_fk FOREIGN KEY (codigomarca) REFERENCES marcas(codigo)
);


INSERT INTO marcas (nome) VALUES ('Nike');
INSERT INTO marcas (nome) VALUES ('Adidas');
INSERT INTO marcas (nome) VALUES ('Colcci');
INSERT INTO marcas (nome) VALUES ('Tommy Hilfiger');
INSERT INTO marcas (nome) VALUES ('Hering');
INSERT INTO marcas (nome) VALUES ('Vans');
INSERT INTO marcas (nome) VALUES ('Vizzano');
INSERT INTO marcas (nome) VALUES ('Aramis');
INSERT INTO marcas (nome) VALUES ('Reserva');

INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Tênis Adidas Performance',345.00, 765, 2);
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Tênis Nike Revolution',769.00 ,1235, 1 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Blusa feminina rosa',99.00, 754, 6 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camisa social branca',180.99, 235, 8 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Bota Chelsea Lacey',322.00, 98, 3 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Blusa moletom Romance',150.76, 324, 3 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camiseta preta base',79.00, 1235, 4 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Bolsa Colcci Lisa',249.00, 112, 3 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camisa Adidas Originals',346.00, 344, 2 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Tênis WM preto',988.00, 2341, 6 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Bota Colcci azul',1540.00, 143, 3 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Scarpin feminino salto',877.00, 673, 7 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camiseta Nike Dri-FIT',124.00 ,228, 1 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camisa polo azul',233.00, 549, 8 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camisa Polo Tommy Hilfiger',499.00, 794, 4 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Sandália Vizzano',1540.00, 83, 7 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Tênis Adidas Superstar',769.00, 326, 2 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camiseta algodão verde',76.99, 1214, 9 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Short Nike Nk',298.00, 683, 1 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camisa Aramis geométrica',355.00, 1033, 8 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Bolsa Nike Unissex',265.29, 596, 1 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Camiseta Aramis vermelha',199.00, 457, 8 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Boné Tommy Jeans',204.64, 68, 4 );
INSERT INTO produtos (nome,valor,estoque,codigomarca) VALUES ('Jaqueta Adidas ECO',609.98, 116, 2);

-- Exibir nome do produto, nome da marca e valor do produto

SELECT
produtos.nome,
marcas.nome,
produtos.valor
FROM produtos

INNER JOIN marcas
ON produtos.codigomarca = marcas.codigo


-- Listar todas as marcas e a quantidade de produtos cadastrados (inclusive 0)


SELECT
marcas.nome,
COUNT(produtos.codigo)
FROM marcas

LEFT JOIN produtos
ON produtos.codigomarca = marcas.codigo

GROUP BY marcas.nome;

-- Exibir o nome do produto e o valor em ordem decrescente

SELECT 
nome,
valor
FROM produtos
ORDER BY valor DESC;

-- Média dos valores dos produtos por marca

SELECT
marcas.nome,
AVG(produtos.valor) AS media
FROM marcas

LEFT JOIN produtos
ON produtos.codigomarca = marcas.codigo

GROUP BY marcas.nome;

-- Listar nome do produto, valor, nome da marca e quantidade em estoque do produto de maior valor (Haverá dois produtos, os dois terão que ser exibidos)

SELECT
produtos.nome,
produtos.valor,
marcas.nome,
produtos.estoque
FROM produtos

INNER JOIN marcas
ON marcas.codigo = produtos.codigomarca

WHERE produtos.valor = (SELECT MAX(produtos.valor) FROM produtos);

-- Listar todos os produtos (exiba todos os dados e converta o código da marca para o nome), onde o estoque esteja entre 500 e 1000 unidades

SELECT
produtos.nome,
produtos.valor,
marcas.nome,
produtos.estoque
FROM produtos

INNER JOIN marcas
ON marcas.codigo = produtos.codigomarca

WHERE produtos.estoque >= 500 AND produtos.estoque <= 1000;

-- Listar todos os produtos (nome, valor e estoque) que contenham os termos: Blusa, Camiseta e Camisa. Exiba em ordem decrescente de preço


SELECT
produtos.nome,
produtos.valor,
marcas.nome,
produtos.estoque
FROM produtos

INNER JOIN marcas
ON marcas.codigo = produtos.codigomarca

WHERE 
UPPER(produtos.nome) LIKE UPPER('%Blusa%') 
OR UPPER(produtos.nome) LIKE UPPER('%Camiseta%') 
OR UPPER(produtos.nome) LIKE UPPER('%Camisa%')

ORDER BY produtos.valor DESC;

-- Exibir a soma dos valores de cada produto e agrupar por marcas que estejam vinculadas em algum produto.


SELECT 
marcas.nome,
SUM(produtos.valor) AS soma
FROM produtos

INNER JOIN marcas
ON marcas.codigo = produtos.codigomarca

GROUP BY marcas.nome;

-- Exibir o nome da marca, onde o produto é o mais caro.


SELECT 
marcas.nome
FROM produtos

INNER JOIN marcas
ON marcas.codigo = produtos.codigomarca

WHERE produtos.valor = (SELECT MAX(produtos.valor) FROM produtos);


-- Listar todos os produtos (nome e estoque), onde a quantidade em estoque seja maior ou igual a média total do estoque contido na tabela de produtos

SELECT
produtos.nome,
produtos.estoque
FROM produtos

WHERE produtos.estoque > (SELECT AVG(produtos.estoque) FROM produtos);

-- Excluir todas as tabelas

DROP TABLE produtos;
DROP TABLE marcas;



